apiVersion: 1

deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    jsonData:
      timeInterval: 15s
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: prometheus

